export default countries = [
    { name: "Egypt", id: 0 },
    { name: "Sudan", id: 1 },
    { name: "Algeria", id: 2 },
    { name: "Morocco", id: 3 },
    { name: "Saudi Arabia", id: 4 },
    { name: "Yemen", id: 5 },
    { name: "Syria", id: 6 },
    { name: "Somalia", id: 7 },
    { name: "Tunisia", id: 8 },
    { name: "Jordan", id: 9 },
    { name: "United Arab Emirates", id: 10 },
    { name: "Palestine", id: 11 },
    { name: "Oman", id: 12 },
    { name: "Kuwait", id: 13 },
    { name: "Qatar", id: 14 },
    { name: "Qatar", id: 15 },
    { name: "Djibouti", id: 16 },
    { name: "Mauritania", id: 17 },
    { name: "Comoros", id: 18 },
  ];
