export default countries = [
    { name: "مصر", id: 0 },
    { name: "سودان", id: 1 },
    { name: "الجزائر", id: 2 },
    { name: "المغرب", id: 3 },
    { name: "لسعودية", id: 4 },
    { name: "اليمن", id: 5 },
    { name: "سوريا", id: 6 },
    { name: "صوماليا", id: 7 },
    { name: "تونس", id: 8 },
    { name: "الاردن", id: 9 },
    { name: "الامارات", id: 10 },
    { name: "فلسطين", id: 11 },
    { name: "عمان", id: 12 },
    { name: "الكويت", id: 13 },
    { name: "قطر", id: 14 },
    { name: "جيبوتي", id: 15 },
    { name: "موريتانيا", id: 17 },
    { name: "قبرص", id: 18 }
  ];
